
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 8;
  public static final int CP = 5;
  public static final int ALL = 2;
  public static final int EOF = 0;
  public static final int AC = 6;
  public static final int PYC = 9;
  public static final int error = 1;
  public static final int CC = 7;
  public static final int CLL = 3;
  public static final int AP = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ALL",
  "CLL",
  "AP",
  "CP",
  "AC",
  "CC",
  "COMA",
  "PYC"
  };
}

