
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 17;
  public static final int AND = 26;
  public static final int LT = 21;
  public static final int IDENT = 28;
  public static final int ELSE = 3;
  public static final int NOTEQ = 20;
  public static final int PLUS = 14;
  public static final int INT = 29;
  public static final int OR = 27;
  public static final int LCURL = 10;
  public static final int SEMI = 12;
  public static final int WHILE = 4;
  public static final int NOT = 25;
  public static final int IF = 2;
  public static final int ASIGN = 13;
  public static final int GT = 23;
  public static final int DO = 5;
  public static final int LTEQ = 22;
  public static final int EOF = 0;
  public static final int DIVIDE = 18;
  public static final int MINUS = 15;
  public static final int PRINT = 7;
  public static final int error = 1;
  public static final int EQ = 19;
  public static final int GTEQ = 24;
  public static final int RPAR = 9;
  public static final int FOR = 6;
  public static final int RCURL = 11;
  public static final int LPAR = 8;
  public static final int UMINUS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "PRINT",
  "LPAR",
  "RPAR",
  "LCURL",
  "RCURL",
  "SEMI",
  "ASIGN",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "DIVIDE",
  "EQ",
  "NOTEQ",
  "LT",
  "LTEQ",
  "GT",
  "GTEQ",
  "NOT",
  "AND",
  "OR",
  "IDENT",
  "INT"
  };
}

